# Args: <cam_file> <obj_file> <output_dir>
{
  "setup": {        
    "blender_install_path": "/home/willer/softwares",
    "blender_version": "blender-2.80-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:2>",
      "output_is_temp": False
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.ObjLoader",
      "config": {
        "path": "<args:1>",
        "axis_forward": "-Z",
        "axis_up": "-Y"
      }
    },
    # {
    #   "name": "lighting.LightSampler",
    #   "config": {
    #     "lights": [
    #       {            
    #         "location": {
    #           "name": "ShellSampler",
    #           "parameters": {
    #             "center": [0, 0, 0],
    #             "radius_min": 40,
    #             "radius_max": 70,
    #             "elevation_min": 15,
    #             "elevation_max": 70
    #           },
    #         },
    #         "type": "POINT",
    #         "energy": 2000,
    #         "color": [255, 255, 255],
    #       }           
    #     ]
    #   }
    # },    
    # {
    #   "name": "lighting.LightLoader",
    #   "config": {
    #     "lights": [
    #       {
    #         "type": "POINT",
    #         "path": "<args:3>",
    #         "file_format": "location rotation color",            
    #         "energy": 1000,            
    #       },          
    #     ]
    #   }
    # },
    {
      "name": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "SUN",
            "location": [0, 60, 60],
            "energy": 1,            
            "color": [255, 255, 255]
          }
        ]
      }
    },
    {
      "name": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation",
        "default_cam_param": {
          "fov": 1,
        }
      }
    },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 350,
        "resolution_x": 512,
        "resolution_y": 512,
      }
    },
    {
      "name": "renderer.NormalRenderer",
      "config": {
        "output_key": "normals",
        "resolution_x": 512,
        "resolution_y": 512,
      }
    },
    {
      "name": "writer.Hdf5Writer",
      "config": {
      }
    },
  ]
}