# Args: <cam_file> <obj_file> <output_dir>
{
  "setup": {    
    #"blender_version": "blender-2.80-linux-glibc217-x86_64",
    "blender_install_path": "/home/willer/softwares",
    "blender_version": "blender-2.80-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:2>",
      "output_is_temp": False
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.ObjLoader",
      "config": {
        "path": "<args:1>",
        "axis_forward": "-Z",
        "axis_up": "-Y"
      }
    },
    {
      "name": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [-100, 100, 0],
            "energy": 100
          }
        ]
      }
    },
    {
      "name": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation",
        "default_cam_param": {
          "fov": 1,
        }
      }
    },
    {
      "name": "renderer.NormalRenderer",
      "config": {
        "output_key": "normals",
        "resolution_x": 512,
        "resolution_y": 512,
      }
    },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 350,
        "resolution_x": 512,
        "resolution_y": 512,
      }
    },
    {
      "name": "writer.Hdf5Writer",
      "config": {
      }
    },
    {
      "name": "writer.CameraStateWriter",
      "config": {       
      }
    }
  ]
}